# fly.toml file generated for billowing-tree-8098 on 2023-04-05T02:47:57+03:00

app = "billowing-tree-8098"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "otp"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
